# -*- coding: utf-8 -*-
"""Hidden jems travel project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMCTgmrfbQTXDk7hZV-MHv9DId3WpMOm
"""

!pip install pandas openpyxl

import pandas as pd

df1 = pd.read_excel("Travel_in_Nagpur_AI_ML_Dataset.xlsx")

df2 = pd.read_excel(
    "Travel_in_Nagpur_Version2_220_Places.xlsx"
)

print(df1.shape)
print(df2.shape)

df = pd.concat(
    [df1, df2],
    ignore_index=True
)

print(df.shape)

df.head()

print(df.columns)

df = df.drop_duplicates()

print(df.shape)

df.to_excel(
    "HiddenJames_Final_Dataset.xlsx",
    index=False
)

def recommend_places(
    category="All",
    season="All"
):

    result = df.copy()

    if category != "All":
        result = result[
            result["Category"] == category
        ]

    if season != "All":
        result = result[
            result["Best_Season"] == season
        ]

    return result

recommend_places(
    category="Nature"
)

def search_place(place):

    result = df[
        df["Place_Name"]
        .str.contains(
            place,
            case=False,
            na=False
        )
    ]

    return result

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# df1 = pd.read_excel(
#     "Travel_in_Nagpur.xlsx"
# )
# 
# df2 = pd.read_excel(
#     "Travel_in_Nagpur_Version2_220_Places.xlsx"
# )
# 
# df = pd.concat(
#     [df1, df2],
#     ignore_index=True
# )
# 
# st.title("Hidden James Travel Guide")
# 
# category = st.selectbox(
#     "Select Category",
#     ["All"] +
#     list(df["Category"].unique())
# )
# 
# if category == "All":
#     result = df
# else:
#     result = df[
#         df["Category"] == category
#     ]
# 
# st.dataframe(result)

!streamlit run app.py &>/content/logs.txt &

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip freeze > requirements.txt

